### ISSUE TITLE
Number of features

### ISSUE THREAD

**Issue by ImageDragon520** [JZK00/Radiomics-Features-Extractor#1]
Hello, I'd like to ask the reason why the number of features you extracted is reduced. Thank you！

**Comment by JZK00** [comment]
Hi, I don't know what is the basis of the reduced number of features you said, and we can choose the number of features we can extract by modifing the parameter file.

**Comment by ImageDragon520** [comment]
I mean cnnresnet, 2048 to 1000. I've fixed it.

**Comment by JZK00** [comment]
OK, here we used all are the pre-trained models from Keras package, which be trained by using ImageNet, and the resnet model is designed for 1000 classes originally. You can see https://keras.io/zh/applications/#resnet.
