### ISSUE TITLE
Many of the extracted feature values of deep learning are 0

### ISSUE THREAD

**Issue by pangda72** [JZK00/Radiomics-Features-Extractor#3]
Hi @JZK00 
Thank you for sharing such great repo,But when I use deep learning networks to extract features from my own data set,I had some problems,many of the extracted feature values of deep learning are 0,as shown in the following table ,So the classification results are terrible.Have you ever come across this situation?I don't know how to solve this problem,Could you give me some help?
[EX_Resnet_FC.csv](https://github.com/JZK00/Radiomics-Features-Extractor/files/8749280/EX_Resnet_FC.csv)

Thanks in advance.
Looking forward to your reply.

Best

**Comment by JZK00** [comment]
Hello, thanks for using the code. The codes here are not the best, they are the pre-trained CNN models, so the extracted features may have some unexplained results. On the one hand, you can train your CNN models by using your data and then extract the DL features. On the other hand, based on your features data now, you can implement some feature selection and reduction algorithms to improve your prediction performance. As you know, the DL features are unexplainable and whatever the features are may all be probable normal.

Hope that may help you~ Good luck.

**Comment by pangda72** [comment]
> Hello, thanks for using the code. The codes here are not the best, they are the pre-trained CNN models, so the extracted features may have some unexplained results. On the one hand, you can train your CNN models by using your data and then extract the DL features. On the other hand, based on your features data now, you can implement some feature selection and reduction algorithms to improve your prediction performance. As you know, the DL features are unexplainable and whatever the features are may all be probable normal.
> 
> Hope that may help you~ Good luck.

Hi@JZK00
Thanks for your prompt reply,I feel very happy.Thanks to your help, I am no longer confused, and I will try it next.

Hope you have a good day.
Best.
