### ISSUE TITLE
what tensorflow version should I need to configure?

### ISSUE THREAD

**Issue by NicoleKenn** [JZK00/Radiomics-Features-Extractor#4]
Hello, thank you for your sharing.
i'm wondering what tensorflow version do you use? tensorflow-gpu=2.4.0 or others?
I wanna configure the environment.
look forward to your reply.
thanks

**Comment by JZK00** [comment]
Hi, 
The codes should not be limited to a specific version but used wherever the Keras is available. 
You can have a try~
