### ISSUE TITLE
Can you process 2D CT images?

### ISSUE THREAD

**Issue by hljWmh** [JZK00/Radiomics-Features-Extractor#5]

**Comment by JZK00** [comment]
Sure, the premise is that you have the corresponding 2D images and segmentation labels (like dicom, nii, etc), as long as the path input is correct. You can handle both 2D or 3D, but you need to make some changes in the YAML configuration file.

**Comment by hljWmh** [comment]
非常感谢您回复，如果方便的话请问我可以加您个微信吗，我是计算机专业研一的，目前在做医学交叉方向，希望有机会可以和您请教一些问题。

**Comment by JZK00** [comment]
好的，可以先邮箱联系我，再加微信。

zekun_jiang@163.com
